---
# tasks file for lae.netbox
- import_tasks: validate_variables.yml
  when: deploy_stage == "packer"

- import_tasks: load_variables.yml

- include_tasks: "install_packages_{{ ansible_pkg_mgr }}.yml"
  when: deploy_stage == "packer"

- name: Switch Ansible's Python interpreter to Python 3
  set_fact:
    ansible_python_interpreter: "{{ netbox_python_binary }}"
  when: deploy_stage == "packer"

- name: Recheck new Python interpreter's version
  setup:
    gather_subset: min
    filter: ansible_python_version
  when: deploy_stage == "packer"

# Can't quite check the effective version of a git installation this early since
# the repo isn't checked out, but most users will be on develop in the first
# place so this dumb check should be good enough.
- name: Ensure the installed Python version is newer than 3.6.0 for NetBox 2.8+
  assert:
    that:
      - "ansible_python_version is version('3.6.0', '>=')"
    msg: >
      NetBox 2.8.0+ requires Python 3.6+. Please either specify an older NetBox
      version, upgrade to a newer distribution that provides Python 3.6+, or
      set netbox_python_binary to an appropriate Python 3.6+ binary.
  when:
    - netbox_stable and netbox_stable_version is version('2.8.0', '>=') or netbox_git
    - deploy_stage == "packer"

- name: Create NetBox user group
  group:
    name: "{{ netbox_group }}"
  when: deploy_stage == "packer"

- name: Create NetBox user and home directory
  user:
    name: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    home: "{{ netbox_home }}"
  when: deploy_stage == "packer"

- name: Create NetBox User .ssh directory
  when: deploy_stage == "packer"
  file:
    path: "{{ netbox_home }}/.ssh"
    state: directory
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"

- name: Create NetBox User id_rsa
  when: deploy_stage == "packer"
  file:
    path: "{{ netbox_home }}/.ssh/"
    state: touch
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: '600'

- name: Add ssh key for bitbucket
  when: deploy_stage == "packer"
  authorized_key:
    user: "{{ netbox_user }}"
    state: present
    key: "{{ lookup('aws_ssm', ssm_path + 'plugin_bb_pk') }}"
    path: "{{ netbox_home }}/.ssh/id_rsa"

- import_tasks: deploy_netbox.yml

- name: Install uWSGI via pip
  pip:
    name: uwsgi
    state: "{{ 'latest' if netbox_keep_uwsgi_updated else 'present' }}"
    umask: "0022"
  environment:
    PATH: "/usr/local/bin:{{ _path }}"
  notify:
    - reload netbox.service
  retries: 2
  register: _netbox_uwsgi_install
  until: _netbox_uwsgi_install is succeeded
  when: deploy_stage == "packer"

- name: Configure uWSGI NetBox application
  template:
    src: uwsgi.ini.j2
    dest: "{{ netbox_shared_path }}/uwsgi.ini"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
  notify:
    - reload netbox.service
  when: deploy_stage == "packer"

- name: Install NetBox socket unit file
  template:
    src: netbox.socket.j2
    dest: /lib/systemd/system/netbox.socket
  notify:
    - restart netbox.socket
  when: deploy_stage == "packer"

- name: Install NetBox service unit file
  template:
    src: netbox.service.j2
    dest: /lib/systemd/system/netbox.service
  notify:
    - restart netbox.service
  when: deploy_stage == "packer"

- name: Install NetBox-rqworker service unit file
  template:
    src: netbox-rqworker.service.j2
    dest: /lib/systemd/system/netbox-rqworker.service
  notify:
    - restart netbox-rqworker.service
  when: deploy_stage == "packer"

- name: Start and enable NetBox' socket and service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - netbox.socket
    - netbox.service
  when: deploy_stage == "packer"

- name: Start and enable netbox-rqworker.service
  systemd:
    name: netbox-rqworker.service
    state: started
    enabled: true
  when: deploy_stage == "packer"

- name: Restore the previous Ansible Python interpreter
  set_fact:
    ansible_python_interpreter: "{{ _netbox_global_python if _netbox_global_python is defined else 'auto_legacy' }}"
  when: deploy_stage == "packer"

- name: Recheck the previous Python interpreter's version
  setup:
    gather_subset: min
    filter: ansible_python_version
  when: deploy_stage == "packer"
